service: minpair-api

provider:
  name: aws
  runtime: python3.7
  memorySize: 3008
  timeout: 20
  environment:
    NLTK_DATA: /opt/nltk_data

package:
  exclude:
    - nltk/**

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: get
      - http:
          path: /vowel
          method: get
    layers:
      - { Ref: NltkCorpusLambdaLayer }

plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux

layers:
  nltkCorpus:
    path: nltk
    name: NltkCorpus
    description: Nltk corpus data.
    compatibleRuntimes:
      - python3.7
